services:
  iptv-filter:
    build: .
    container_name: mytvlist-filter
    restart: unless-stopped
    environment:
      OUTPUT_DIR: /app/data
      UPDATE_INTERVAL_SECONDS: "21600"
      CHECK_STREAMS: "0"
      GH_PROXY: ""
    volumes:
      - iptv_data:/app/data

  web:
    image: nginx:alpine
    container_name: mytvlist-web
    restart: unless-stopped
    ports:
      - "28024:80"
    volumes:
      - iptv_data:/usr/share/nginx/html:ro
    depends_on:
      - iptv-filter

volumes:
  iptv_data:
